/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.code.squad.product.manager.view;

import javax.swing.JOptionPane;
import com.code.squad.product.manager.controller.ProductController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marcelo.moraes
 */
public class CadastrarProdutos extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarProdutos
     */
    private String modoTela;

    public CadastrarProdutos() {
        initComponents();
        setLocationRelativeTo(null);
        desabilitadorDosCampos();
        dispose();
    }

    //função para habilitar o cadastro de produtos
    public void habilitadorDosCampos() {
        IDTexto.setEditable(false);
        DataTexto.setEditable(false);
        NomeTexto.setEditable(true);
        DescricaoTexto.setEditable(true);
        QuantidadeTexto.setEditable(true);
        PrecoCompraTexto.setEditable(true);
        PrecoVendaTexto.setEditable(true);

        salvar.setEnabled(true);
        cancelar.setEnabled(true);
        Atualizar.setEnabled(false);
        Listar.setEnabled(false);
        Excluir.setEnabled(false);

    }

    //função para iniciar desabilitada o preenchimento do formulário 
    public void desabilitadorDosCampos() {
        IDTexto.setEditable(false);
        DataTexto.setEditable(false);
        NomeTexto.setEditable(false);
        DescricaoTexto.setEditable(false);
        QuantidadeTexto.setEditable(false);
        PrecoCompraTexto.setEditable(false);
        PrecoVendaTexto.setEditable(false);

        salvar.setEnabled(false);
        cancelar.setEnabled(false);
        Voltar.setEnabled(true);
    }

    //limpa os campos preenchidos para realizar um novo cadastro de produto 
    public void limparCamposDados() {
        IDTexto.setText("");
        DataTexto.setText("");
        NomeTexto.setText("");
        DescricaoTexto.setText("");
        QuantidadeTexto.setText("");
        PrecoCompraTexto.setText("");
        PrecoVendaTexto.setText("");

    }

    //validação se os campos foram preenchidos ou não
    private boolean validadorDeCampos() {

        if (this.NomeTexto.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Cadastre o nome do produto!");
            return false;
        }

        if (this.DescricaoTexto.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Cadastre uma descrição para o produto!");
            return false;
        }

        if (this.QuantidadeTexto.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Cadastre a quantidade do produto!");
            return false;
        }

        if (this.PrecoCompraTexto.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Cadastre o preço que o produto foi comprado!");
            return false;
        }

        if (this.PrecoVendaTexto.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Cadastre o preço que o produto será vendido!");
            return false;
        }
        return true;
    }

    public void LoadTable() throws SQLException {

        //Peço ao controller resgatar os produtos  do banco de dados
        ArrayList<String[]> linhasProdutos = ProductController.getProdutos();

        DefaultTableModel tmProdutos = (DefaultTableModel) this.tblProduto.getModel();
        //Limpo a tabela, excluindo todas as linhas
        tmProdutos.setRowCount(0);

        //Para cada produto resgatado do banco de dados, atualizo a tabela
        linhasProdutos.forEach((c) -> {
            tmProdutos.addRow(c);
        });

        //Defino o tamanho para cada coluna
        tblProduto.getColumnModel().getColumn(0).setPreferredWidth(300); //Codigo do item
        tblProduto.getColumnModel().getColumn(1).setPreferredWidth(250); // Data
        tblProduto.getColumnModel().getColumn(2).setPreferredWidth(200); // Nome
        tblProduto.getColumnModel().getColumn(3).setPreferredWidth(300); // Descricao
        tblProduto.getColumnModel().getColumn(3).setPreferredWidth(300); // Quantidade
        tblProduto.getColumnModel().getColumn(3).setPreferredWidth(300); // PrecoCompra
        tblProduto.getColumnModel().getColumn(3).setPreferredWidth(300); // PrecoVenda
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ESCOLHAS = new javax.swing.ButtonGroup();
        ProductPainel = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        PainelCentral = new javax.swing.JPanel();
        ID = new javax.swing.JLabel();
        IDTexto = new javax.swing.JTextField();
        Data = new javax.swing.JLabel();
        DataTexto = new javax.swing.JTextField();
        Nome = new javax.swing.JLabel();
        NomeTexto = new javax.swing.JTextField();
        Descricao = new javax.swing.JLabel();
        DescricaoTexto = new javax.swing.JTextField();
        Quantidade = new javax.swing.JLabel();
        QuantidadeTexto = new javax.swing.JTextField();
        PrecoCompra = new javax.swing.JLabel();
        PrecoCompraTexto = new javax.swing.JTextField();
        PrecoVenda = new javax.swing.JLabel();
        PrecoVendaTexto = new javax.swing.JTextField();
        Habilitado = new javax.swing.JRadioButton();
        Desabilitado = new javax.swing.JRadioButton();
        Incluir = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        Listar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        TabelaDeDados = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ProductPainel.setBackground(new java.awt.Color(255, 255, 255));
        ProductPainel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Titulo.setText("CADASTRO DE PRODUTOS");

        PainelCentral.setBackground(new java.awt.Color(255, 255, 255));
        PainelCentral.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ID.setBackground(new java.awt.Color(255, 255, 255));
        ID.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ID.setText("ID:");

        Data.setBackground(new java.awt.Color(255, 255, 255));
        Data.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Data.setText("Data:");

        Nome.setBackground(new java.awt.Color(255, 255, 255));
        Nome.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Nome.setText("Nome:");

        Descricao.setBackground(new java.awt.Color(255, 255, 255));
        Descricao.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Descricao.setText("Descrição:");

        Quantidade.setBackground(new java.awt.Color(255, 255, 255));
        Quantidade.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Quantidade.setText("Quantidade:");

        PrecoCompra.setBackground(new java.awt.Color(255, 255, 255));
        PrecoCompra.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        PrecoCompra.setText("Preço de Compra: ");

        PrecoVenda.setBackground(new java.awt.Color(255, 255, 255));
        PrecoVenda.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        PrecoVenda.setText("Preço de Venda: ");

        Habilitado.setBackground(new java.awt.Color(255, 255, 255));
        ESCOLHAS.add(Habilitado);
        Habilitado.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Habilitado.setText("HABILITADO");

        Desabilitado.setBackground(new java.awt.Color(255, 255, 255));
        ESCOLHAS.add(Desabilitado);
        Desabilitado.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Desabilitado.setText("DESABILITADO");

        javax.swing.GroupLayout PainelCentralLayout = new javax.swing.GroupLayout(PainelCentral);
        PainelCentral.setLayout(PainelCentralLayout);
        PainelCentralLayout.setHorizontalGroup(
            PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelCentralLayout.createSequentialGroup()
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Data)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DataTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Descricao))
                    .addGroup(PainelCentralLayout.createSequentialGroup()
                        .addComponent(Quantidade)
                        .addGap(3, 3, 3)
                        .addComponent(QuantidadeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PrecoCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PrecoCompraTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(PrecoVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PrecoVendaTexto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescricaoTexto)
                    .addGroup(PainelCentralLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Habilitado)
                        .addGap(11, 11, 11)
                        .addComponent(Desabilitado)))
                .addContainerGap())
        );
        PainelCentralLayout.setVerticalGroup(
            PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(IDTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data)
                    .addComponent(DataTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nome)
                    .addComponent(NomeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descricao)
                    .addComponent(DescricaoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quantidade)
                    .addComponent(QuantidadeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecoCompra)
                    .addComponent(PrecoCompraTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecoVenda)
                    .addComponent(PrecoVendaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Habilitado)
                    .addComponent(Desabilitado))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        Incluir.setBackground(new java.awt.Color(255, 255, 255));
        Incluir.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        Incluir.setText("INCLUIR");
        Incluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncluirActionPerformed(evt);
            }
        });

        Atualizar.setBackground(new java.awt.Color(255, 255, 255));
        Atualizar.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        Atualizar.setText("ATUALIZAR");
        Atualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });

        Listar.setBackground(new java.awt.Color(255, 255, 255));
        Listar.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        Listar.setText("LISTAR");
        Listar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Excluir.setBackground(new java.awt.Color(255, 255, 255));
        Excluir.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        Excluir.setText("EXCLUIR");
        Excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        salvar.setBackground(new java.awt.Color(255, 255, 255));
        salvar.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        salvar.setText("SALVAR");
        salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(255, 255, 255));
        cancelar.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        cancelar.setText("CANCELAR");
        cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TabelaDeDados.setViewportView(tblProduto);

        Voltar.setText("VOLTAR");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductPainelLayout = new javax.swing.GroupLayout(ProductPainel);
        ProductPainel.setLayout(ProductPainelLayout);
        ProductPainelLayout.setHorizontalGroup(
            ProductPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPainelLayout.createSequentialGroup()
                .addGroup(ProductPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductPainelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Voltar)
                        .addGap(193, 193, 193)
                        .addComponent(Titulo))
                    .addGroup(ProductPainelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(ProductPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PainelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ProductPainelLayout.createSequentialGroup()
                                .addComponent(Incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(Atualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Listar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Excluir)
                                .addGap(5, 5, 5)
                                .addComponent(salvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ProductPainelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TabelaDeDados)))
                .addContainerGap())
        );
        ProductPainelLayout.setVerticalGroup(
            ProductPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProductPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo)
                    .addComponent(Voltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ProductPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Incluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salvar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(TabelaDeDados, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProductPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProductPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //retorno ao menu main
    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        Menu menu = new Menu();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncluirActionPerformed
        habilitadorDosCampos();
    }//GEN-LAST:event_IncluirActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        if (validadorDeCampos()) {

        }
    }//GEN-LAST:event_salvarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        desabilitadorDosCampos();
        limparCamposDados();
    }//GEN-LAST:event_cancelarActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        //Verifico se há linhas para poder editar
        if (tblProduto.getRowCount() > 0) {
            //Verifico se o usuário selecionou alguma linha (Primeira linha = 0)
            if (tblProduto.getSelectedRow() >= 0) {

                habilitadorDosCampos();

                //Variável acessória para identifcar se o formulário está em modo de edição ou alteração
                modoTela = "Editar";
                //Atribuo os valores que estão na linha selecionada para a tabela
                NomeTexto.setText(tblProduto.getModel().getValueAt(tblProduto.getSelectedRow(), 1).toString());
                DescricaoTexto.setText(tblProduto.getModel().getValueAt(tblProduto.getSelectedRow(), 2).toString());
                QuantidadeTexto.setText(tblProduto.getModel().getValueAt(tblProduto.getSelectedRow(), 3).toString());
                PrecoCompraTexto.setText(tblProduto.getModel().getValueAt(tblProduto.getSelectedRow(), 4).toString());
                PrecoVendaTexto.setText(tblProduto.getModel().getValueAt(tblProduto.getSelectedRow(), 5).toString());

            } else {
                JOptionPane.showMessageDialog(this, "Selecione um produto para editar!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não há produtos para editar!");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_AtualizarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        if (tblProduto.getRowCount() > 0) {
            int numeroLinha = tblProduto.getSelectedRow();
            if (ProductController.excluir(Integer.parseInt(tblProduto.getValueAt(numeroLinha, 0).toString()))) {
                try {
                    this.LoadTable();
                } catch (SQLException ex) {
                    Logger.getLogger(CadastrarProdutos.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this, "Produto excluído da base de dados");
            } else {
                JOptionPane.showMessageDialog(this, "Falha ao excluir o produto!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não há produtos para excluir!");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_ExcluirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JLabel Data;
    private javax.swing.JTextField DataTexto;
    private javax.swing.JRadioButton Desabilitado;
    private javax.swing.JLabel Descricao;
    private javax.swing.JTextField DescricaoTexto;
    private javax.swing.ButtonGroup ESCOLHAS;
    private javax.swing.JButton Excluir;
    private javax.swing.JRadioButton Habilitado;
    private javax.swing.JLabel ID;
    private javax.swing.JTextField IDTexto;
    private javax.swing.JButton Incluir;
    private javax.swing.JButton Listar;
    private javax.swing.JLabel Nome;
    private javax.swing.JTextField NomeTexto;
    private javax.swing.JPanel PainelCentral;
    private javax.swing.JLabel PrecoCompra;
    private javax.swing.JTextField PrecoCompraTexto;
    private javax.swing.JLabel PrecoVenda;
    private javax.swing.JTextField PrecoVendaTexto;
    private javax.swing.JPanel ProductPainel;
    private javax.swing.JLabel Quantidade;
    private javax.swing.JTextField QuantidadeTexto;
    private javax.swing.JScrollPane TabelaDeDados;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton salvar;
    private javax.swing.JTable tblProduto;
    // End of variables declaration//GEN-END:variables
}
