/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.code.squad.product.manager.view;

/**
 *
 * @author marcelo.moraes
 */
public class CadastrarProdutos extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarProdutos
     */
    public CadastrarProdutos() {
        initComponents();
        setLocationRelativeTo(null);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ESCOLHAS = new javax.swing.ButtonGroup();
        ProductPainel = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        PainelCentral = new javax.swing.JPanel();
        ID = new javax.swing.JLabel();
        IDTexto = new javax.swing.JTextField();
        Data = new javax.swing.JLabel();
        DataTexto = new javax.swing.JTextField();
        Nome = new javax.swing.JLabel();
        NomeTexto = new javax.swing.JTextField();
        Descricao = new javax.swing.JLabel();
        DescricaoTexto = new javax.swing.JTextField();
        Quantidade = new javax.swing.JLabel();
        QuantidadeTexto = new javax.swing.JTextField();
        PrecoCompra = new javax.swing.JLabel();
        PrecoCompraTexto = new javax.swing.JTextField();
        PrecoVenda = new javax.swing.JLabel();
        PrecoVendaTexto = new javax.swing.JTextField();
        Habilitado = new javax.swing.JRadioButton();
        Desabilitado = new javax.swing.JRadioButton();
        Incluir = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        Listar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        TabelaDeDados = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ProductPainel.setBackground(new java.awt.Color(255, 255, 255));
        ProductPainel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        Titulo.setText("CADASTRO DE PRODUTOS");

        PainelCentral.setBackground(new java.awt.Color(255, 255, 255));
        PainelCentral.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ID.setBackground(new java.awt.Color(255, 255, 255));
        ID.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ID.setText("ID:");

        Data.setBackground(new java.awt.Color(255, 255, 255));
        Data.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Data.setText("Data:");

        Nome.setBackground(new java.awt.Color(255, 255, 255));
        Nome.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Nome.setText("Nome:");

        Descricao.setBackground(new java.awt.Color(255, 255, 255));
        Descricao.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Descricao.setText("Descrição:");

        Quantidade.setBackground(new java.awt.Color(255, 255, 255));
        Quantidade.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Quantidade.setText("Quantidade:");

        PrecoCompra.setBackground(new java.awt.Color(255, 255, 255));
        PrecoCompra.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        PrecoCompra.setText("Preço de Compra: ");

        PrecoVenda.setBackground(new java.awt.Color(255, 255, 255));
        PrecoVenda.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        PrecoVenda.setText("Preço de Venda: ");

        Habilitado.setBackground(new java.awt.Color(255, 255, 255));
        Habilitado.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Habilitado.setText("HABILITADO");

        Desabilitado.setBackground(new java.awt.Color(255, 255, 255));
        Desabilitado.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Desabilitado.setText("DESABILITADO");

        javax.swing.GroupLayout PainelCentralLayout = new javax.swing.GroupLayout(PainelCentral);
        PainelCentral.setLayout(PainelCentralLayout);
        PainelCentralLayout.setHorizontalGroup(
            PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelCentralLayout.createSequentialGroup()
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Data)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DataTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Descricao))
                    .addGroup(PainelCentralLayout.createSequentialGroup()
                        .addComponent(Quantidade)
                        .addGap(3, 3, 3)
                        .addComponent(QuantidadeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PrecoCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PrecoCompraTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(PrecoVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PrecoVendaTexto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DescricaoTexto)
                    .addGroup(PainelCentralLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Habilitado)
                        .addGap(11, 11, 11)
                        .addComponent(Desabilitado)))
                .addContainerGap())
        );
        PainelCentralLayout.setVerticalGroup(
            PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(IDTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Data)
                    .addComponent(DataTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nome)
                    .addComponent(NomeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descricao)
                    .addComponent(DescricaoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quantidade)
                    .addComponent(QuantidadeTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecoCompra)
                    .addComponent(PrecoCompraTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecoVenda)
                    .addComponent(PrecoVendaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Habilitado)
                    .addComponent(Desabilitado))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        Incluir.setBackground(new java.awt.Color(255, 255, 255));
        Incluir.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        Incluir.setText("INCLUIR");
        Incluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Atualizar.setBackground(new java.awt.Color(255, 255, 255));
        Atualizar.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        Atualizar.setText("ATUALIZAR");
        Atualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Listar.setBackground(new java.awt.Color(255, 255, 255));
        Listar.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        Listar.setText("LISTAR");
        Listar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Excluir.setBackground(new java.awt.Color(255, 255, 255));
        Excluir.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        Excluir.setText("EXCLUIR");
        Excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jButton2.setText("SALVAR");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jButton1.setText("CANCELAR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TabelaDeDados.setViewportView(jTable1);

        Voltar.setText("VOLTAR");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductPainelLayout = new javax.swing.GroupLayout(ProductPainel);
        ProductPainel.setLayout(ProductPainelLayout);
        ProductPainelLayout.setHorizontalGroup(
            ProductPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPainelLayout.createSequentialGroup()
                .addGroup(ProductPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductPainelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Voltar)
                        .addGap(193, 193, 193)
                        .addComponent(Titulo))
                    .addGroup(ProductPainelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(ProductPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PainelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ProductPainelLayout.createSequentialGroup()
                                .addComponent(Incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(Atualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Listar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Excluir)
                                .addGap(5, 5, 5)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(ProductPainelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TabelaDeDados)))
                .addContainerGap())
        );
        ProductPainelLayout.setVerticalGroup(
            ProductPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProductPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo)
                    .addComponent(Voltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ProductPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Incluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(TabelaDeDados, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProductPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProductPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //retorno ao menu main
    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        Menu menu = new Menu();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JLabel Data;
    private javax.swing.JTextField DataTexto;
    private javax.swing.JRadioButton Desabilitado;
    private javax.swing.JLabel Descricao;
    private javax.swing.JTextField DescricaoTexto;
    private javax.swing.ButtonGroup ESCOLHAS;
    private javax.swing.JButton Excluir;
    private javax.swing.JRadioButton Habilitado;
    private javax.swing.JLabel ID;
    private javax.swing.JTextField IDTexto;
    private javax.swing.JButton Incluir;
    private javax.swing.JButton Listar;
    private javax.swing.JLabel Nome;
    private javax.swing.JTextField NomeTexto;
    private javax.swing.JPanel PainelCentral;
    private javax.swing.JLabel PrecoCompra;
    private javax.swing.JTextField PrecoCompraTexto;
    private javax.swing.JLabel PrecoVenda;
    private javax.swing.JTextField PrecoVendaTexto;
    private javax.swing.JPanel ProductPainel;
    private javax.swing.JLabel Quantidade;
    private javax.swing.JTextField QuantidadeTexto;
    private javax.swing.JScrollPane TabelaDeDados;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
